In [2]:
import numpy as np
# 4,8,9

In [25]:
 # 1. How to Creating a 3x3 Identity Matrix with Float Data Type? 

identity_matrix1 = np.identity(3, dtype=float)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [19]:
# 2. Create a 1D Array with Random Values between 0 and 1. 
array = np.random.rand(5)
array_2 = np.array(array)
print(array_2)

[0.4490909  0.98812729 0.63300463 0.5335727  0.51288844]


In [10]:
# 3. Create a 2D Array with Random Integer Values. 

rows, cols = 4, 5  
low, high = 10, 50  
array_3 = np.random.randint(low, high, size=(rows, cols))

print(array_3)


[[31 18 39 10 36]
 [39 38 20 12 11]
 [19 41 36 33 25]
 [25 39 18 30 34]]


In [ ]:
# 4. Creating an Array Using a Custom Function. 

In [11]:
# 5. Reshaping a 1D Array into a 2D Array
array_1D = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(array_1D)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [14]:
array_5 = array_1D.reshape(4,3)
print(array_5)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [17]:
# 6.How to Creating a 3x3 Array of Ones?
array_6 = np.ones((3,3), dtype = float)
print(array_6)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [21]:
# 7. How to get the common items between two pythons NumPy?
a = np. array ([1,2,3,2,3,4,3,4,5,6]) 
b = np. array ([7,2,10,2,7,4,9,4,9,8])
array_7 = np.intersect1d(a, b)
print (array_7)

[2 4]


In [27]:
# 8. From array a remove all items present in array b
a = np. array ([1,2,3,4,5]) 
b = np. array ([5,6,7,8,9]) 
array_8 = a-b
print(array_8)

[-4 -4 -4 -4 -4]


In [ ]:
# 9. Limit the number of items printed in python NumPy array a to a maximum of 6 elements.

In [ ]:
# 10. Drop all nan values from a 1D NumPy

In [29]:
#11. Question: Create a 1D NumPy array of the first 20 natural numbers and a 2D NumPy array of shape (4, 5) with values ranging from 1 to 20. 
array_11 = np.arange(1,21)
print(array_11)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [31]:
array_11_reshape = array_11.reshape(4,5)
print(array_11_reshape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [5]:
# 12. Question: Given a 3D NumPy array of shape (2, 3, 4), find its shape, size, number of dimensions, and data type. Change its data type to float64 
# and verify the change. 
array_12 = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[13,14,15,16],[17,18,19,20],[21,22,23,24]]])
print(array_12)
print(array_12.shape)
print(array_12.size)
print(array_12.ndim)
print(array_12.dtype)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
(2, 3, 4)
24
3
int64


In [8]:
# 13. Question: Reshape a 1D array of 12 elements into a 3x4 2D array and then flatten it back into a 1D array using ravel (). Verify that the flattened 
# array matches the original. 
array_13 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(array)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [9]:
array_13_reshape = array_13.reshape(3,4)
print(array_13_reshape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [10]:
array_13_flatten = array_13_reshape.ravel()
print(array_13_flatten)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [14]:
# 14. Question: Given two arrays, a = np. array ([1, 2, 3]) and b = np. array ([4,5, 6]), perform element-wise addition, subtraction, multiplication, 
# and division. Explain the behavior when dividing by zero. 

a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([0,0,0])

print(a)
print(b)
print(c)

addition = a+b
subtraction = a-b
multiplication = a*b
division = a/b
zero_division_a = c/a
zero_division_b = c/b

print("addition :-" ,addition)
print("subtraction :-" ,subtraction)
print("multiplication :-" ,multiplication)
print("division :-" ,division)
print("zero division a :-" ,zero_division_a)
print("zero division b :-" , zero_division_b)

[1 2 3]
[4 5 6]
[0 0 0]
addition :- [5 7 9]
subtraction :- [-3 -3 -3]
multiplication :- [ 4 10 18]
division :- [0.25 0.4  0.5 ]
zero division a :- [0. 0. 0.]
zero division b :- [0. 0. 0.]


In [10]:
# 15. Question: Create a 2D array of shape (3, 1) and a 1D array of length 3. Perform element-wise addition using broadcasting. Explain how broadcasting 
# rules apply in this scenario.
array_2d = np.array([[1],[2],[3]])
array_1d = np.array([10,20,30])

print(array_2d)
print(array_1d)

array_15 = array_1d + array_2d
print(array_15)

[[1]
 [2]
 [3]]
[10 20 30]
[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [ ]:
# 16. Question: Generate a random 2D array of integers between 0 and 10. Use conditional operators to create a Boolean mask identifying elements 
# greater than 5. Replace all elements greater than 5 with the value 5.

In [19]:
# 17. Question: Given a 4x4 array of random integers, use indexing and slicing to extract: 
# o The entire second row 
# o The last column 
# o The subarray consisting of the first two rows and first two columns

array = np.random.randint(0, 10, size=(4, 4))
print("array :-",array)

second_row = array[1, :] 
print("second row :-", second_row)

last_column = array[:, -1]
print("last column :-", last_column)

subarray = array[:2, :2]  
print("subarray :-", subarray)

array :- [[3 4 4 4]
 [8 8 2 0]
 [3 0 8 4]
 [5 5 8 1]]
second row :- [8 8 2 0]
last column :- [4 0 4 1]
subarray :- [[3 4]
 [8 8]]


In [ ]:
# 18. Question: Describe a practical example where NumPy can be used in EDA, AI, ML, and DL, and implement a NumPy solution for a simple task in each 
# area. 

# 1. Exploratory Data Analysis (EDA)
# Analyzing a dataset to compute statistical metrics like mean, median, standard deviation, or identifying missing values.

# 2. Artificial Intelligence (AI)
# AI applications often involve vector and matrix operations for tasks like natural language processing or search optimization.

# 3. Machine Learning (ML)
# Preprocessing data for ML models, such as normalizing features or encoding categorical variables.

# 4. Deep Learning (DL)
# NumPy is often used for initializing weights, computing activations, or data preparation before feeding it to DL frameworks like TensorFlow or PyTorch.

In [33]:
# 20. Question: Create a 1D array of 27 elements and reshape it into a 3x3x3 3D array. Flatten it back into a 1D array and compare the flattened array 
# with the original.

array = np.arange(1,28)
print("array :-", array)

array_20 = array.reshape(3,3,3)
print("arry 20 :-", array_20)

flatten_20 = array_20.flatten()
print("flatten array :-", flatten_20)

compare_array = np.array_equal(array, flatten_20)
print("compare array :-", compare_array)

array :- [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27]
arry 20 :- [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
flatten array :- [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27]
compare array :- True


In [4]:
# 21. Question: Perform matrix multiplication of two 2D arrays using np.dot () and @. Compare the results and performance of both methods using a 
# large dataset. 

array_a = np.array([[1,2,3],[4,5,6]])
array_b = np.array([[7,8,9],[10,11,12]])

array_dot = np.dot(array_a,array_b)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [7]:
# 22. Question: Create a 3D array of shape (2, 1, 4) and a 2D array of shape (4, 1). Perform an element-wise operation using broadcasting and explain
# the result. Use np. new axis to achieve the same result without broadcasting.

array_3d = np.array([[[1, 2, 3, 4]], [[5, 6, 7, 8]]]) 
array_2d = np.array([[10], [20], [30], [40]]) 

# element-wise addition with broadcasting
result_broadcast = array_3d + array_2d.T
print(result_broadcast)

[[[11 22 33 44]]

 [[15 26 37 48]]]


In [8]:
# 23. Question: Generate a 2D array of random floats between 0 and 1. Use conditional operators to create a Boolean mask for values less than 0.5. 
# Replace these values with their squares and leave the rest unchanged.

# 2D array of random floats between 0 and 1
array_2d = np.random.rand(4, 4) 
print("Original Array:\n", array_2d)

# Boolean mask for values less than 0.5
mask = array_2d < 0.5
print("\nBoolean Mask (Values < 0.5):\n", mask)

# Replace values less than 0.5 with their squares
array_2d[mask] = array_2d[mask] ** 2
print("\nModified Array:\n", array_2d)


Original Array:
 [[0.1556507  0.22593556 0.86027946 0.90043975]
 [0.24201498 0.28790473 0.0712609  0.45308529]
 [0.91919638 0.46957355 0.08160757 0.35210983]
 [0.4169913  0.50736642 0.15525809 0.78359101]]

Boolean Mask (Values < 0.5):
 [[ True  True False False]
 [ True  True  True  True]
 [False  True  True  True]
 [ True False  True False]]

Modified Array:
 [[0.02422714 0.05104688 0.86027946 0.90043975]
 [0.05857125 0.08288913 0.00507812 0.20528628]
 [0.91919638 0.22049932 0.00665979 0.12398133]
 [0.17388175 0.50736642 0.02410508 0.78359101]]


In [12]:
# 24. Question: Given a 5x5 array of sequential integers, use slicing to: 
# o Extract the diagonal elements 
# o Replace the elements of the middle row with zeros 
# o Flip the array vertically and horizontally 

array_5d = np.arange(1, 26).reshape(5, 5)
print("5D array:-", array_5d)

diagonal_elements = np.diag(array_5d)
print("Diagonal Elements:-", diagonal_elements)

array_5d[2, :] = 0  
print("Array after replacing the middle row with zeros:-", array_5d)

flipped_array = array_5d[::-1, ::-1]
print("Array after flipping vertically and horizontally:-", flipped_array)

5D array:- [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Diagonal Elements:- [ 1  7 13 19 25]
Array after replacing the middle row with zeros:- [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 0  0  0  0  0]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Array after flipping vertically and horizontally:- [[25 24 23 22 21]
 [20 19 18 17 16]
 [ 0  0  0  0  0]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


In [14]:
# 25. Question: Create a 4D array of shape (2, 3, 4, 5) with random integers. Use advanced slicing to extract a subarray and compute the mean along a 
# specified axis. 

array_4d = np.random.randint(1, 100, size=(2, 3, 4, 5))
print("4D Array:-", array_4d)

subarray = array_4d[0, :, :, :2]
print("Extracted Subarray :-".format(subarray.shape), subarray)

4D Array:- [[[[88 70 46 10 70]
   [72 17 54 14 73]
   [52 98 22 71 55]
   [87 37 71  4  7]]

  [[15 36 93 89 37]
   [17 27 53 39  7]
   [63 92  4 72 79]
   [88 80 16 44 68]]

  [[65 92 53 36  5]
   [66 24 89 81  6]
   [35 85 98 26 95]
   [84 56 72 23  5]]]


 [[[13 24 25 86 23]
   [52 58 67 77 54]
   [91 68 31 92 57]
   [32 89  5  5  7]]

  [[95 99 11 99 92]
   [ 9 67 21 38 82]
   [30 66  8 76 57]
   [65 57 71 17 75]]

  [[ 6 99 64 74 68]
   [65  8  4 72 75]
   [93 85 68 14 25]
   [99 70 71 31 26]]]]
Extracted Subarray :- [[[88 70]
  [72 17]
  [52 98]
  [87 37]]

 [[15 36]
  [17 27]
  [63 92]
  [88 80]]

 [[65 92]
  [66 24]
  [35 85]
  [84 56]]]


In [20]:
# 26. Question: Given an array of shape (10, 20), reshape it to (20, 10) and (5, 40). Discuss the impact on the array's shape, size, and dimensionality.

array_1 = np.arange(200).reshape(10, 20)
print("(10, 20) array:-", array_1)

array_2 = array_1.reshape(20, 10)
print("(20, 10):- ", array_2)

array_3 = array_1.reshape(5, 40)
print("Reshaped Array Shape (5, 40):-", array_3)

(10, 20) array:- [[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
   18  19]
 [ 20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37
   38  39]
 [ 40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57
   58  59]
 [ 60  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77
   78  79]
 [ 80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97
   98  99]
 [100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
  118 119]
 [120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
  138 139]
 [140 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157
  158 159]
 [160 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177
  178 179]
 [180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
  198 199]]
(20, 10):-  [[  0   1   2   3   4   5   6   7   8   9]
 [ 10  11  12  13  14  15  16  17  18  19]
 [ 20  21  22  23  24  25  26  27 

In [21]:
# 27. Question: Generate a large 2D array and demonstrate the use of np. reshape () and unravel () to manipulate its shape for various linear algebra 
# operations. 

array_2d = np.random.randint(1, 100, size=(6, 8))
print("2D array :-", array_2d)

reshaped_array_1 = array_2d.reshape(4, 12)
print("Reshaped Array:-\n", reshaped_array_1)

2D array :- [[68  3 72 37 34 85 41 27]
 [23 77 19 98 34 62 32 56]
 [94  1 30 66 51 66 51 41]
 [42 62 60 85 52 39 59 32]
 [43 27 15 76 17 54 92 74]
 [63 39 97  3 89 81 50 61]]
Reshaped Array:-
 [[68  3 72 37 34 85 41 27 23 77 19 98]
 [34 62 32 56 94  1 30 66 51 66 51 41]
 [42 62 60 85 52 39 59 32 43 27 15 76]
 [17 54 92 74 63 39 97  3 89 81 50 61]]


In [25]:
# 28. Question: Given a 6x6 matrix, use advanced indexing and slicing to extract the upper triangular part of the matrix and set the lower triangular
# part to zero. Verify the result.

matrix = np.random.randint(1, 100, size=(6, 6))
print(" Matrix:-", matrix)

upper_triangular = np.triu(matrix)  
print("Upper Triangular :-", upper_triangular)

lower_triangular_indices = np.tril_indices_from(matrix, k=-1)  
matrix[lower_triangular_indices] = 0  
print("\nMatrix after Setting Lower Triangular Part to Zero:\n", matrix)

verification = np.array_equal(matrix, upper_triangular)
print("\nVerification Result:", verification)


 Matrix:- [[92 67  7 50  4 52]
 [ 9 96 78  6 24  6]
 [ 4 44 79 37 22 41]
 [27 57 61 37 97 60]
 [34 94 81 18 30 75]
 [ 8 12 28 89 22 23]]
Upper Triangular :- [[92 67  7 50  4 52]
 [ 0 96 78  6 24  6]
 [ 0  0 79 37 22 41]
 [ 0  0  0 37 97 60]
 [ 0  0  0  0 30 75]
 [ 0  0  0  0  0 23]]

Matrix after Setting Lower Triangular Part to Zero:
 [[92 67  7 50  4 52]
 [ 0 96 78  6 24  6]
 [ 0  0 79 37 22 41]
 [ 0  0  0 37 97 60]
 [ 0  0  0  0 30 75]
 [ 0  0  0  0  0 23]]

Verification Result: True
